### ISSUE TITLE
Recirculation duration?

### ISSUE THREAD

**Issue by Bleh55** [dustindclark/homebridge-rinnai-controlr#1]
In Settings, Recirculation Duration is set at 15 minutes. When creating HomeKit automation, I set a time to start, and use the option to turn off after 2 hours. I was expecting the recirculation to go on for the full two hours, but it turns off after the 15 minutes. I could change the duration in settings to match or something longer than my longest automation duration, but It would be nice to keep the “manual” toggle to a shorter duration. Anyway to implement separate durations? Or some other way to make my use case work?

**Comment by dustindclark** [comment]
How would you like to see this work? A recirculation switch for each configured duration? I can't think of many clean approaches.

**Comment by Bleh55** [comment]
I hadn’t really thought it through, but maybe a switch for each pre-defined duration, and then the option to hide a switch that you wouldn’t normally trigger manually. Is it possible to have a switch hidden but still have it update the status?

**Comment by buckzilla** [comment]
Within the Control-R app (which is terribly crappy) you can do scheduled re-circulation events AND separately, a point in time re-circulation.  This is fine, but not very fine grained.  I'm very excited to have this plug-in, where I can tell Siri to do a point in time re-circulation.  Knowing it will be 15 minutes per my configuration is fine.  From a scheduling perspective I would like to try something like 10 minutes of re-circulation every 30 minutes, during a time frame.  I could do this via homekit automation I believe.. right?

**Comment by wrmacj** [comment]
I think what you want is built into the Control-R App and further according to the Control-R users guild and Rinnai support, what you are trying to do may not be possible, based on time frames.  It is very dependaant on if you have a dedicated loop(Highly recomentded) or or cross over.  From the guide - PG-5
4 .If the water heater accepts the request to start recirculation, the pump turns on and runs for 5 min(Designated time) OR until the water temp is reached(Whichever occurs first).
5. After recircul;ation completes, the pump enters intpo a Mandatory dormant (inactive) state. **During this time, the pump will not turn on for ANY reason, even if the push button or motion sensor is activated.**
For example with dedicated loop and temp set to 130F max the inactive state in Economy mode is 22 minutes and in Comfort mode it is 11 minutes Mandatory incactive.  It changes with the Max temp setting.  @ 140 it is 18min and 9 min.  
It also changes if you have an internal pump model or external pump model.
The Control-R user guide spells this all out very clearly.  I think that it is possible that people expect the Control-r to do things that it has been programed not to do.  That interpace is a standalone interphace that has built in saftey features.  It was not designed to be a gateway.
That being said....It is desigend to do what you want it do, by default with out complex control of HA.....
If you set the system as indicated above to 130 in comfort mode for 1hr @7am it will heat your dedicated loop to 130 and then go dormant for 11 min in comfort mode and then will check the temp to see if it needs to reheat the loop.  
The users guild is very helpful and you may find that your tast is a lot easier than you think.  
BTW....All this changes when they introduce the new model Control-R comming around end of Oct 2022, I am told.

**Comment by dustindclark** [comment]
Closing this out since this is currently a limitation in ControlR. In general, I think scheduling use cases are probably better suited for the manufacturer-provided app. I don't just mean in water heaters, think thermostats, pool equipment, etc. Managing scheduled automations across platforms is both more difficult to manage and less reliable. Devices should follow the schedule even if Wi-Fi goes down, and HomeKit can't do that.
