### ISSUE TITLE
Recirculation always on

### ISSUE THREAD

**Issue by guillochon** [dustindclark/homebridge-rinnai-controlr#12]
**Describe The Bug:**
My water heater seems to be perpetually in "recirculation" mode. In the Control-R app it always shows as "recirculating" and in Apple Home the device's status is always on. If I send an off command, the Home accessory shows as off for a little bit (maybe 10ish seconds), but immediately flips back on. The heater itself is not recirculating in this state, however when I power cycle the heater it immediately starts recirculating. It then will not recirculate again until the next power cycle.

It's entirely possible my heater is just in a weird state but it's strange that my attempts to turn off recirculation after power cycling are ignored.

**Logs:**

This is mean trying to toggle the heater off, those attempts are logged. I don't see anything else in the logs.

```
[06/10/2022, 16:42:14] [RinnaiControlR] setRecirculateActive to false for device null
[06/10/2022, 16:42:21] [RinnaiControlR] setRecirculateActive to true for device null
[06/10/2022, 16:42:26] [RinnaiControlR] setRecirculateActive to false for device null
[06/10/2022, 16:43:15] [RinnaiControlR] setRecirculateActive to false for device null
```

**Plugin Config:**

```json
        {
            "username": "---",
            "password": "---",
            "recirculationDuration": 5,
            "temperatureUnits": "F",
            "minimumTemperature": 120,
            "maximumTemperature": 140,
            "platform": "RinnaiControlR"
        },
```

**Environment:**

* **Plugin Version**: 1.0.16
* **Homebridge Version**: 1.5.0
* **Node.js Version**: v16.16.0
* **NPM Version**: 8.11.0
* **Operating System**: hb-service

**Comment by dustindclark** [comment]
Can you try cutting power to you Ctrl-R device for a few seconds, then restoring? I have noticed that mine occasionally goes unresponsive. In fact, I ended up putting my water heater on a smart plug, and creating an automation that cuts and restores power every day. Sad, I know.

**Comment by guillochon** [comment]
I wasn't aware there was a way to cut the power only to the control-r unit, for me it's hooked up to my heater via a pair of wires...how do you do that?

I mentioned in the OP that I tried power cycling the whole heater (which includes the control-r unit), but that didn't work to get it out of its funky state.

I did seem to get it back into a working state by taking off the front cover of the heater and toggling the on/off button for the temperature controller. But that's super inconvenient as you might imagine...why they buried those buttons behind the front panel is beyond me.

**Comment by dustindclark** [comment]
If you cut the power to the entire unit for long enough (10 secs or so), the ctrl-r loses power as well. I know it's an inconvenient solution, but there's no way around the Rinnai firmware. Clearly their server-side stuff is plagued with similar problems.

**Comment by dustindclark** [comment]
Closing as issue appears to be resolved. Re-open if that's not the case.
