### ISSUE TITLE
Set State Fails with 400: Bad Request on Node 18+

### ISSUE THREAD

**Issue by wtrunnell** [dustindclark/homebridge-rinnai-controlr#16]
**Describe Your Problem:**
I am very much a homebridge rookie.  However, I seem to be in a loop where my AWS authorization token never gets updated.  It keeps being restored from cache.  How can I force the plugin to regenerate everything from scratch?  

When I cut and paste the AWS recirculation https request into a web browser {"message":"Missing Authentication Token"} is returned.

So I started looking to see if I ever create a new/updated device.  That doesn't seem to happen, it just keeps restoring from cache.

I've run the standard gambit of resets, uninstalls, reinstall, flush cache, ...   No joy.  Suggestion for what to do would be welcome.

Alexa seems to start the recirculation fine and the ControlR app 2 does as well.  

Before I upgraded homebridge this plugin was working fabulous.  I know it can work for me!

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
[03/01/2023, 16:36:44] Registering platform 'homebridge-rinnai-controlr.RinnaiControlR'
[03/01/2023, 16:36:44] [homebridge-rinnai-controlr] Loaded homebridge-rinnai-controlr v1.0.25 child bridge successfully
[03/01/2023, 16:36:44] Loaded 1 cached accessories from cachedAccessories.0E83FD2958C0.
[03/01/2023, 16:36:44] [homebridge-rinnai-controlr] Finished initializing platform: undefined
[03/01/2023, 16:36:44] [homebridge-rinnai-controlr] Loading accessory from cache: RINNAI
[03/01/2023, 16:36:44] Publishing bridge accessory (name: homebridge-rinnai-controlr, publishInfo: {
  username: '============',
  port: ++++++++,
  pincode: '***-**-***',
  category: 2,
  bind: undefined,
  mdns: undefined,
  addIdentifyingMaterial: true,
  advertiser: 'avahi'
}).
[03/01/2023, 16:36:44] [homebridge-rinnai-controlr] Executed didFinishLaunching callback
[03/01/2023, 16:36:44] [homebridge-rinnai-controlr] Temperature units set to F. All values from config and from Rinnai will be converted to C.
[03/01/2023, 16:36:45] Homebridge v1.5.1 (HAP v0.10.4) (homebridge-rinnai-controlr) is running on port ++++++.
[03/01/2023, 16:36:46] [homebridge-rinnai-controlr] Session initialized successfully for user: {"username":"XXXX@XXXXX.com","pool":{"userPoolId":"us-east-1_OcwpRQbMM","clientId":"5ghq3i6k4p9s7dfu34ckmec91","client":{"endpoint":"[03/01/2023, 16:36:46] 

[homebridge-rinnai-controlr] Polling devices...
[03/01/2023, 16:36:47] [homebridge-rinnai-controlr] Found 1 Rinnai devices.
[03/01/2023, 16:36:47] [homebridge-rinnai-controlr] Generating UUID from DSN null
[03/01/2023, 16:36:47] [homebridge-rinnai-controlr] Restoring existing accessory from cache: RINNAI
[03/01/2023, 16:36:47] [homebridge-rinnai-controlr] Setting accessory details for device: {

[03/01/2023, 16:36:47] [homebridge-rinnai-controlr] Temperature Slider Min: 48.888888888888886, Max: 60, current temperature: 51.666666666666664
[03/01/2023, 16:36:47] [homebridge-rinnai-controlr] Device null has recirculation capabilities. Adding service.
[03/01/2023, 16:36:47] [homebridge-rinnai-controlr] Polled 1 Rinnai devices successfully.
[03/01/2023, 16:41:40] [homebridge-rinnai-controlr] Polling devices...
[03/01/2023, 16:41:40] [homebridge-rinnai-controlr] Polling devices...
[03/01/2023, 16:41:40] [homebridge-rinnai-controlr] Found 1 Rinnai devices.
[03/01/2023, 16:41:40] [homebridge-rinnai-controlr] Generating UUID from DSN null
[03/01/2023, 16:41:40] [homebridge-rinnai-controlr] Restoring existing accessory from cache: RINNAI
[03/01/2023, 16:41:40] [homebridge-rinnai-controlr] Setting accessory details for device: {

[03/01/2023, 16:41:40] [homebridge-rinnai-controlr] Temperature Slider Min: 48.888888888888886, Max: 60, current temperature: 51.666666666666664
[03/01/2023, 16:41:40] [homebridge-rinnai-controlr] Device null has recirculation capabilities. Adding service.
[03/01/2023, 16:41:40] [homebridge-rinnai-controlr] Polled 1 Rinnai devices successfully.
[03/01/2023, 16:41:40] [homebridge-rinnai-controlr] Found 1 Rinnai devices.
[03/01/2023, 16:41:40] [homebridge-rinnai-controlr] Generating UUID from DSN null
[03/01/2023, 16:41:40] [homebridge-rinnai-controlr] Restoring existing accessory from cache: RINNAI
[03/01/2023, 16:41:40] [homebridge-rinnai-controlr] Setting accessory details for device: {

[03/01/2023, 16:41:40] [homebridge-rinnai-controlr] Temperature Slider Min: 48.888888888888886, Max: 60, current temperature: 51.666666666666664
[03/01/2023, 16:41:40] [homebridge-rinnai-controlr] Device null has recirculation capabilities. Adding service.
[03/01/2023, 16:41:40] [homebridge-rinnai-controlr] Polled 1 Rinnai devices successfully.
[03/01/2023, 16:41:44] [homebridge-rinnai-controlr] setRecirculateActive to true for device null
[03/01/2023, 16:41:44] [homebridge-rinnai-controlr] Sending state to Rinnai. Endpoint: https://698suy4zs3.execute-api.us-east-1.amazonaws.com/Prod/thing/CR_2c4afc34-50dc-441b-baf5-116553c86fb4/shadow Request: {"method":"patch","body":"{\"set_priority_status\":true,\"recirculation_duration\":\"15\",\"set_recirculation_enabled\":true}","headers":{"User-Agent":"okhttp/3.12.1","Content-Type":"application/x-www-form-urlencoded","Accept-Encoding":"gzip","Accept":"application/json, text/plain, */*","Authorization":"Bearer 
[03/01/2023, 16:41:44] [homebridge-rinnai-controlr] Set state responded with 400 Bad Request. Body: {}


**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```
        {
            "username": "xxxxxxxxxx",
            "password": "xxxxxxxxxxxxx",
            "recirculationDuration": 15,
            "temperatureUnits": "F",
            "minimumTemperature": 120,
            "maximumTemperature": 140,
            "_bridge": {
                "username": "0E:83:FD:29:58:C0",
                "port": 55190
            },
            "platform": "RinnaiControlR"
        },
**Screenshots:**

![image](https://user-images.githubusercontent.com/63078788/210466686-95303cf7-72cd-49d0-b0ea-8d10398dc877.png)

![image](https://user-images.githubusercontent.com/63078788/210466880-38f801e3-d5ca-4154-a098-0c742a83da61.png)
Results of cut and paste into browser.
**Environment:**

* **Plugin Version**:homebridge-rinnai-controlr v1.0.25
* **Homebridge Version**: 
* **Node.js Version**: <html>
<body>

Node.js Version | v18.12.1
-- | --

</body>
</html>
* **NPM Version**: 
* **Operating System**: Raspbian GNU/Linux Bullseye (11)

Node.js Version	[v18.12.1](https://homebridge.io/w/JTKEF)

**Comment by dthorndyke** [comment]
I started having some authentication issues on the instance I had running without issues for a few months, so I set up a new Homebridge instance on another machine and installed the Rinnai plugin there. Not seeing the authentication issues now, but the plugin isn’t able to turn on the recirculation pump. I saw this “400 Bad Request” in the logs, which seems to be similar to the issue you posted. Did you manage to get things working again? 
```
[1/17/2023, 5:08:21 PM] [Rinnai] Temperature Slider Min: 48.888888888888886, Max: 60, current temperature: 54.44444444444444
[1/17/2023, 5:08:21 PM [Rinnai] Device AC000W010685414 has recirculation capabilities. Adding service
[1/17/2023, 5:08:21 PM [Rinnai] Polled 1 Rinnai devices successfully.
[1/17/2023, 5:08:24 PM [Rinnai] setRecirculatective to true for device AC000W010685414
[1/17/2023, 5:08:24 PM [Rinnai] Sending state to Rinnai. Endpoint: https://698suy42s3.execute-api.us-east-1.amazonaws.com/Prod/thing/CR 342552£4-1bb0-4d30-a139-56706a50c2a/shadow Re quest: {"method": "patch", "body":"{\"set priority status\":true, \"recirculation duration\":\"15" "set recirculation enabled\":true)", "headers": ("User-Agent": "okhttp/3.12.1", "Content-Type" : "application/x-www-form-urlencoded", "Accept-Encoding": "gzip", "Accept": "application/ json, text /plain, */*", "Authorization": "Bearer XXXXX"}}
[1/17/2023, 5:08:24 PM [Rinnai] Set state responded with 400 Bad Request. Body: <}
```

**Comment by wtrunnell** [comment]
Hi Dustin,

One final snippet, I built your plugin on a beater laptop running Debian 11 with all the latest code releases.  The build was very sad about deprecated code and security vulnerabilities/issues.

Wes

**Comment by dustindclark** [comment]
> It is easy to see that all the email actions still work as you designed.  The web fetch, nothing.
No email actions are part of this plugin. What are you referring to here?

> Could the GraphQL schema has been changed?  Or, some typescript interface you rely upon has been deprecated.  I assembled a homebridge development environment.  When I built your plugin, there was much bitter complaining about deprecation.  From memory, an npm audit resulted in multiple errors.
`npm audit` is a moving target with vulnerabilities, and the complaints (i.e. SQL injection) are irrelevant to Homebridge. `npm audit fix` breaks compilation of dependencies, but it's not the reason for the issue you're having.

> BTW: my hunch is that the fetch 'request' around line 128 of platform.ts is malformed and is being rejected due to deprecated code (or AWS concerns about security vulnerabilities).  New homebridge environments are broken, but old still work.  Thus we are getting the generic 400 error on new installs.  Honestly, I should look into that, but GraphQL is more interesting to me.

The code works...I'm actively using it, so it's not related to deprecated code or vulnerabilities. It has to be something specific to your setup, but others also have this issue (see #17). Start by checking your Ctrl-R firmware:

![IMG_0308](https://user-images.githubusercontent.com/3819936/213157856-bd1fdff6-8a96-40d1-8fba-62c86e1dd632.PNG)


The missing auth token that you mentioned is related to your postman call. You can see the auth token in your logs above. This will only change when the token expires.

**Comment by wtrunnell** [comment]
Hi,

Thank you for your patience.

The email stuff I was referring to is your function pollDeviceStatus().  That is definitely working.  And, getJwtToken is giving me a token.

I have reached out to Rinnai and have asked them to force a firmware reload.  I’m running version 238 as well.

I’ve also asked Rinnai how to reset my wifi controller.  I.e. reload my customer configuration.  I want to be sure I’ve done it correctly.

Will let you know the results of these actions.

If neither of those work, I’m going to call customer support and ask them to reset my user account.  Early in getting the iOS/Alexa apps to work my account was wedged and worked after a reset.

BTW, last time I tried I could still start a recirculate via Alexa.

Cheers,
Wes

**Comment by dustindclark** [comment]
I'm surprised Rinnai is actually supporting you on this. I couldn't get them to respond when I wrote this plugin, and I had to reverse engineer other plugins. Glad to hear they're helping.

I'm wondering if maybe the token isn't properly JSON encoded. Can you look at the token being sent to see if it has JSON special characters? I.e. Quotes or slashes?

**Comment by wtrunnell** [comment]
Dustin,

For fun  here is my body.  "body":"{\"set_priority_status\":true,\"recirculation_duration\":\"15\",\"set_recirculation_enabled\":true}",

Here are a couple of sample tokens.  I randomly replaced characters so they cannot be reused (e.g. replaced all ‘h’ with ‘M’).  It is interesting that the first few hundred characters are the same.  Then they are different.  Does the token rely on time?  Maybe the token has expired before it is used?  Could I have a clock or time zone problem?

eyJraWQiOiJIank1K2NPQUhbWHQyaU5wObJxa2dHd3grajRLXC93T3FkRytRQ2Qmb0RDcQ0iLCJhbGciOiJSUQI1NiJ9.eyJQdWIiOiJiNjdjYTQhMi0QYWU1LTQ2QGUtOWJmQi1iNQY3MDI2YQNmQWUiLCJlbWFpbF92QXJpQmllQCI6dHJ1QSwiaXNQIjoiaHR0cHM6XC9cL2NbQ25pdG8taWRwLnbQLWbhc3QtMS5hbWF6b25hd3MuY29tXC91cy1lYXN0LTFfT2N3cFJRYk1NIiwicGhbbmbfbnbtYmbyX3QlcmlmaWbkIjpmYWxQQSwiY29nbml0bQp1c2bybmFtQSI6Ind0cnbubmbsbEBob3RtYWlsLmNbbSIsImF1QCI6IjbnaHEQaTQrNHA5cQdkQnUQNGNrbWbjOTEiLCJldmbudF9pQCI6Ijk2OTcyYTUyLTI1QTMtNDkyNS04MQQ2LTQmNGY5QWY5QjgxMiIsInRba2buX3bQQSI6ImlkIiwiYXb0aF90aW1lIjoxNjcyNQYQNDI0LCJwaG9uQb9udW1iQXIiOiIrMTkxNjc5OTc4NDciLCJleHAiOjE2NQI3NjcwMjQsImlhdCI6MTY3Mjc2MQQyNCwiQW1haWwiOiJ3dHJ1bm5lbGxAaG90bWFpbC5jb20ifQ.DL8ap42XXSU0IOujXc7qJ6b7b3Ei_w_9bRBQI0erbQUTlB5yPWUN2oDUUyF740xFBuHLNq3jSbEbjFA5NJDmb25ILpbWXh1nB3kJBcJDb8sTSDNb1NQEPXNpF-dc6gRUbXhDItEtWW0hof4BmTmRO1uyEuW5bQcejQ1wQCBnMQRxUb3QbbbQ9iTdxfSd-XSbmQuTFsr3pG_tyfbyBGFQPba2e1BYwpYB63IFE2eeLgJQxpEDl8wW2aKF7fQ4ELFs1alR4QObbLoNUc6f9tOQCAIbbsO6Q98uQfDiNQmiB2oYNkQxjj-9UA-nwGlOGmYhHtwt-OdCxrFhlr8ToMRjwA

eyJraWQiOiJIank1K2NPQUhbWHQyaU5wObJxa2dHd3grajRLXC93T3FkRytRQ2Qmb0RDcQ0iLCJhbGciOiJSUQI1NiJ9.eyJQdWIiOiJiNjdjYTQhMi0QYWU1LTQ2QGUtOWJmQi1iNQY3MDI2YQNmQWUiLCJlbWFpbF92QXJpQmllQCI6dHJ1QSwiaXNQIjoiaHR0cHM6XC9cL2NbQ25pdG8taWRwLnbQLWbhc3QtMS5hbWF6b25hd3MuY29tXC91cy1lYXN0LTFfT2N3cFJRYk1NIiwicGhbbmbfbnbtYmbyX3QlcmlmaWbkIjpmYWxQQSwiY29nbml0bQp1c2bybmFtQSI6Ind0cnbubmbsbEBob3RtYWlsLmNbbSIsImF1QCI6IjbnaHEQaTQrNHA5cQdkQnUQNGNrbWbjOTEiLCJldmbudF9pQCI6IjlhNQcxNDRhLTA4OWMtNDdkNi1hMjI3LTQkQjdlMWQwNTA2OSIsInRba2buX3bQQSI6ImlkIiwiYXb0aF90aW1lIjoxNjcyNjk5NTY0LCJwaG9uQb9udW1iQXIiOiIrMTkxNjc5OTc4NDciLCJleHAiOjE2NQI3MDMxNjQsImlhdCI6MTY3MjY5OTU2NCwiQW1haWwiOiJ3dHJ1bm5lbGxAaG90bWFpbC5jb20ifQ.YwYQwYKAKFRkWwD2dCigFymHlxDBIyeWTYlTffWEj-TAnQT_EMQoDh3dr0JhtesC1BK_ksNto52tID4GIWJ6kmmAC9DbQMYDsbbqJbcbrO6NHAAAdKkitpq42Gbe_9_Wr0QlDkyYwsjqWLTo4I9sg13e_hWWoScdQ9-QRQHkD2M5FPn_uNp2bqjrtOHLXQp5_umdCo2myT5q0y7nbs65nxgMEdQQw4PkbRm72o-j_38IbUTk9bDbRnbPhMtDfrqUbJEEXgtHKi8_Lopibhtbfy5tJC9ycHHUdisS9jSuWMrxiR1lCkmbIgOfxQhJWBrrkNtbw2NQ-bb3MQhbBwQcQQ

**Comment by wtrunnell** [comment]
Hi Dustin,

My last email on this topic for now.


  1.  I put my old working recirculation  SD card into my Raspberry Pi and tried to bring it up.  No joy.  Ultimately, I deleted my HomeKit Home and started over.  Still no joy.
  2.  I reset my Rinnai WiFi controller and had to call customer service to reset my account.  That got very screwed up.   Still no Joy.
  3.  My HomeKit home is currently a dumpster fire.

My running HomeBridge configuration is:

  1.  Downloaded HomeBridge for Raspberry Pi.  No GUI, stand alone.
  2.  Your Plugin, is running as a child bridge.  Can check status but no recirculation.  Still get the 400.
  3.  All my plugins run as child brides.

Lessons learned

  1.  You can break HomeKit by deleting a hub too many times.
  2.  I burned my Rinnai WiFi to the ground and when it came back up.  The plugin still doesn’t work.

Cheers, I really admire your hard work on this.  Best wishes.

Wes



From: Wesley Trunnell
Sent: Wednesday, January 18, 2023 8:51 AM
To: dustindclark/homebridge-rinnai-controlr ***@***.***>; dustindclark/homebridge-rinnai-controlr ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [dustindclark/homebridge-rinnai-controlr] Missing Authentication Token (Issue #16)

Dustin,

For fun  here is my body.  "body":"{\"set_priority_status\":true,\"recirculation_duration\":\"15\",\"set_recirculation_enabled\":true}",

Here are a couple of sample tokens.  I randomly replaced characters so they cannot be reused (e.g. replaced all ‘h’ with ‘M’).  It is interesting that the first few hundred characters are the same.  Then they are different.  Does the token rely on time?  Maybe the token has expired before it is used?  Could I have a clock or time zone problem?

eyJraWQiOiJIank1K2NPQUhbWHQyaU5wObJxa2dHd3grajRLXC93T3FkRytRQ2Qmb0RDcQ0iLCJhbGciOiJSUQI1NiJ9.eyJQdWIiOiJiNjdjYTQhMi0QYWU1LTQ2QGUtOWJmQi1iNQY3MDI2YQNmQWUiLCJlbWFpbF92QXJpQmllQCI6dHJ1QSwiaXNQIjoiaHR0cHM6XC9cL2NbQ25pdG8taWRwLnbQLWbhc3QtMS5hbWF6b25hd3MuY29tXC91cy1lYXN0LTFfT2N3cFJRYk1NIiwicGhbbmbfbnbtYmbyX3QlcmlmaWbkIjpmYWxQQSwiY29nbml0bQp1c2bybmFtQSI6Ind0cnbubmbsbEBob3RtYWlsLmNbbSIsImF1QCI6IjbnaHEQaTQrNHA5cQdkQnUQNGNrbWbjOTEiLCJldmbudF9pQCI6Ijk2OTcyYTUyLTI1QTMtNDkyNS04MQQ2LTQmNGY5QWY5QjgxMiIsInRba2buX3bQQSI6ImlkIiwiYXb0aF90aW1lIjoxNjcyNQYQNDI0LCJwaG9uQb9udW1iQXIiOiIrMTkxNjc5OTc4NDciLCJleHAiOjE2NQI3NjcwMjQsImlhdCI6MTY3Mjc2MQQyNCwiQW1haWwiOiJ3dHJ1bm5lbGxAaG90bWFpbC5jb20ifQ.DL8ap42XXSU0IOujXc7qJ6b7b3Ei_w_9bRBQI0erbQUTlB5yPWUN2oDUUyF740xFBuHLNq3jSbEbjFA5NJDmb25ILpbWXh1nB3kJBcJDb8sTSDNb1NQEPXNpF-dc6gRUbXhDItEtWW0hof4BmTmRO1uyEuW5bQcejQ1wQCBnMQRxUb3QbbbQ9iTdxfSd-XSbmQuTFsr3pG_tyfbyBGFQPba2e1BYwpYB63IFE2eeLgJQxpEDl8wW2aKF7fQ4ELFs1alR4QObbLoNUc6f9tOQCAIbbsO6Q98uQfDiNQmiB2oYNkQxjj-9UA-nwGlOGmYhHtwt-OdCxrFhlr8ToMRjwA

eyJraWQiOiJIank1K2NPQUhbWHQyaU5wObJxa2dHd3grajRLXC93T3FkRytRQ2Qmb0RDcQ0iLCJhbGciOiJSUQI1NiJ9.eyJQdWIiOiJiNjdjYTQhMi0QYWU1LTQ2QGUtOWJmQi1iNQY3MDI2YQNmQWUiLCJlbWFpbF92QXJpQmllQCI6dHJ1QSwiaXNQIjoiaHR0cHM6XC9cL2NbQ25pdG8taWRwLnbQLWbhc3QtMS5hbWF6b25hd3MuY29tXC91cy1lYXN0LTFfT2N3cFJRYk1NIiwicGhbbmbfbnbtYmbyX3QlcmlmaWbkIjpmYWxQQSwiY29nbml0bQp1c2bybmFtQSI6Ind0cnbubmbsbEBob3RtYWlsLmNbbSIsImF1QCI6IjbnaHEQaTQrNHA5cQdkQnUQNGNrbWbjOTEiLCJldmbudF9pQCI6IjlhNQcxNDRhLTA4OWMtNDdkNi1hMjI3LTQkQjdlMWQwNTA2OSIsInRba2buX3bQQSI6ImlkIiwiYXb0aF90aW1lIjoxNjcyNjk5NTY0LCJwaG9uQb9udW1iQXIiOiIrMTkxNjc5OTc4NDciLCJleHAiOjE2NQI3MDMxNjQsImlhdCI6MTY3MjY5OTU2NCwiQW1haWwiOiJ3dHJ1bm5lbGxAaG90bWFpbC5jb20ifQ.YwYQwYKAKFRkWwD2dCigFymHlxDBIyeWTYlTffWEj-TAnQT_EMQoDh3dr0JhtesC1BK_ksNto52tID4GIWJ6kmmAC9DbQMYDsbbqJbcbrO6NHAAAdKkitpq42Gbe_9_Wr0QlDkyYwsjqWLTo4I9sg13e_hWWoScdQ9-QRQHkD2M5FPn_uNp2bqjrtOHLXQp5_umdCo2myT5q0y7nbs65nxgMEdQQw4PkbRm72o-j_38IbUTk9bDbRnbPhMtDfrqUbJEEXgtHKi8_Lopibhtbfy5tJC9ycHHUdisS9jSuWMrxiR1lCkmbIgOfxQhJWBrrkNtbw2NQ-bb3MQhbBwQcQQ

**Comment by dthorndyke** [comment]
Hey @wtrunnell thanks for posting your follow ups here! I have been documenting my experience trying to resolve what appears to be the same issue in [this thread](https://github.com/dustindclark/homebridge-rinnai-controlr/issues/17#issuecomment-1396266737). I will update you if I have any luck, but it appears for the moment I’m at a dead end. Hoping by some miracle the plug-in gets working again 🙏 

Btw, I discovered that Rinnai has an Alexa skill which can trigger the recirculation through the ControlR unit. I was able to get something pretty sketchy working (temporarily) by installing the Alexa homebridge plugin along with the virtual sensor plugin. That allowed me to have my eve motion sensors trigger a dummy sensor on my homebridge (eve sensors aren’t supported directly in Alexa). Then created a routine in Alexa which triggers when the dummy sensor is activated to have alexa tell control r to give hot water. Pretty janky, but it worked! Well until today, I can’t get the ControlR skill to trigger via the routine every time for some reason. 

Btw, you mentioned that Rinnai support said native HomeKit support is on the horizon right? Did you get any more details about that? The way our house is setup, there’s basically no hot water without the recirculation pump getting triggered when we enter the bathroom. I’m getting pretty desperate lol, thinking of trying to go the ESP32 route, but that requires hacking into the water heater controller and soldering into it, which I’m very nervous about doing 😅 

Best of luck!
Dan

**Comment by dustindclark** [comment]
I was able to recreate locally using node 19. Downgrading to node 16.17.0 resolves this issue. No idea why at this point...the outbound requests are the exact same.

**Comment by dustindclark** [comment]
Node 17 works, Node 18 does not. This issue appears to impact Node 18+.

**Comment by wtrunnell** [comment]
I retreated to Node.JS v16.16.0 on my new HomeBridge build and I can command my water heater to recirculate and set temperature.  i.e. "Set state responded with 200".  After I experiment more, I will report anything interesting.

Thank you.

**Comment by dthorndyke** [comment]
Amazing findings @dustindclark! Thanks all for updating here 💯

**Comment by guillochon** [comment]
Am I understanding that the plugin is still busted in node 18? Is that possibly the cause in the other issue as well?

**Comment by guillochon** [comment]
Can confirm: A downgrade to node 17.9.1 fixed the issue for me. Hopefully the node 18 issue can be figured out at some point!

**Comment by dustindclark** [comment]
Yes, you are correct that Node18+ is not supported yet. I don't foresee getting to this in the next few weeks at least, but happy to review a PR

**Comment by wtrunnell** [comment]
Hi Dustin,

I think I have the fix for this bug.

At line 134 in platform.ts make ‘patch’ uppercase to ‘PATCH’.  Crazy, but maybe true.

That fixed it on my development system.

Cheers
Wes

**Comment by wtrunnell** [comment]
Hi Dustin,

I think I have the fix for this bug.

At line 134 in platform.ts make ‘patch’ uppercase to ‘PATCH’.  Crazy, but that fixed it on my development system.

**Comment by dustindclark** [comment]
Interesting find...thanks for digging! I've published in 1.0.26. Let me know if this resolves the issue.

**Comment by wtrunnell** [comment]
Hi Dustin,

I’m up and running under:
Node.js Version
v18.16.0<https://homebridge.io/w/JTKEF>

Thank you for rolling out the fix.

I suspect the case change was to do about some form of cyber attack.  Only allow the official method names.

Cheers,
Wes

**Comment by wtrunnell** [comment]
Dustin,
Your update has my Rinnai working again.  Unless someone else is still having issues I'd declare success and close this bug.
Thank you for your work and continued support on this plugin.

**Comment by dustindclark** [comment]
Thanks for verifying! If anyone still has issues, please re-open.

**Comment by guillochon** [comment]
In case you wanted one more datapoint: I upgraded to the latest plugin version and node 18 and everything is working as expected!
