### ISSUE TITLE
Question: State Info?

### ISSUE THREAD

**Issue by EricSabe** [dustindclark/homebridge-rinnai-controlr#5]
I'm considering adding the wifi module to my Rinnai - so I can't test this myself.

What kind of state information is available?  Are events generated when the heat or recirc is running?

Ty!

**Comment by dustindclark** [comment]
Recirc is exposed as a switch, so you can create automations that toggle this or automations that are triggered by this. Heating state is not currently available.

**Comment by guillochon** [comment]
@dustindclark Could I get some clarification here: is it *technically* impossible to retrieve the state from Rinnai, or is it just not implemented in this plugin?
